activate.yml update

diff --git a/.github/workflows/activate.yml b/.github/workflows/activate.yml
--- a/.github/workflows/activate.yml
+++ b/.github/workflows/activate.yml
@@ -1,50 +1,36 @@
-name: Test project
+name: Acquire activation file
 
-on: [push, pull_request]
+on:
+  workflow_dispatch:
 
 jobs:
-  testAllModes:
-    name: Test in ${{ matrix.testMode }}
+  activation:
+    name: Request manual activation file 🔑
     runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        projectPath:
-          - test-project
-        testMode:
-          - playmode
-          - editmode
-          - standalone
     steps:
-      - uses: actions/checkout@v4
+      # Checkout repository (required to test local actions)
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      # Request manual activation file
+      - name: Request manual activation file
+        id: getManualLicenseFile
+        continue-on-error: true
+        uses: ./
+
+      - name: Check for failure
+        run: |
+          if [ "${{ steps.getManualLicenseFile.outcome }}" != "failure"  ]; then
+            echo "Expected failure, got ${{ steps.getManualLicenseFile.outcome }}"
+            exit 1
+          fi
+      # Request manual activation file
+      - name: Unity - Request Activation File
+        id: requestActivationFile
+        uses: game-ci/unity-request-activation-file@v2.0-alpha-1
+      - name: Upload activation file
+        uses: actions/upload-artifact@v2
         with:
-          lfs: true
-      - uses: actions/cache@v3
-        with:
-          path: ${{ matrix.projectPath }}/Library
-          key: Library-${{ matrix.projectPath }}
-          restore-keys: |
-            Library-
-      - uses: game-ci/unity-test-runner@v4
-        id: tests
-        env:
-          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
-          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
-          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
-        with:
-          projectPath: ${{ matrix.projectPath }}
-          testMode: ${{ matrix.testMode }}
-          artifactsPath: ${{ matrix.testMode }}-artifacts
-          githubToken: ${{ secrets.GITHUB_TOKEN }}
-          checkName: ${{ matrix.testMode }} Test Results
-          coverageOptions: 'generateAdditionalMetrics;generateHtmlReport;generateBadgeReport;assemblyFilters:+my.assembly.*'
-      - uses: actions/upload-artifact@v3
-        if: always()
-        with:
-          name: Test results for ${{ matrix.testMode }}
-          path: ${{ steps.tests.outputs.artifactsPath }}
-      - uses: actions/upload-artifact@v3
-        if: always()
-        with:
-          name: Coverage results for ${{ matrix.testMode }}
-          path: ${{ steps.tests.outputs.coveragePath }}
+          name: ${{ steps.requestActivationFile.outputs.filePath }}
+          path: ${{ steps.requestActivationFile.outputs.filePath }}
+          retention-days: 3
